### PR TITLE
Escape Message Preview Links At Any Position In The Message Content

### LINKED ISSUE #125: ! Not working mid-sentence to ignore message reference
Currently an embed will still be generated if the message doesn't start with ! + Message link

Bug fix has to make it so ! Can be used anywhere in the message.

Also changing ! To <> to keep bot symbols consistent with discord.

### PR DESCRIPTION
**Pull request by BlackBearFTW**
This bugfix makes sure the discord message refrence url escape characters can be used anywhere.

Also `!link` has been changed to `<link>` to keep the discord bot consistent with discords methods

### CODE REVIEW

**Comment by BlackBearFTW** [comment]
Yeah I still have to write tests

**Comment by BlackBearFTW** [comment]
Tests have been written, all done now. 

Thank you for the collab, hope ill get to do some more in the future!

File: src/event/handlers/DiscordMessageLinkHandler.ts [hunk 1]
```diff
@@ -11,10 +11,15 @@ class DiscordMessageLinkHandler extends EventHandler {
 		const messagePreviewService = MessagePreviewService.getInstance();
 		const messageRegex = /https:\/\/(ptb\.)?discord(app)?\.com\/channels\//gm;
 
-		if (message.content.startsWith("!")) return;
-
 		if (message.content.match(messageRegex)) {
 			const linkIndex = message.content.search(messageRegex);
+
+			// Gets the position of the url from a string
```
Comment (LamboCreeper) [inline src/event/handlers/DiscordMessageLinkHandler.ts]: Useless comment, code is self explanatory!

**Review by LamboCreeper — APPROVED** [review]
Looks good! Thanks 🙂

**Comment by BlackBearFTW** [comment]
I removed the comment!

File: src/event/handlers/DiscordMessageLinkHandler.ts (hunk 1 above)
Comment (BlackBearFTW) [reply src/event/handlers/DiscordMessageLinkHandler.ts]: Removed 👍

File: src/event/handlers/DiscordMessageLinkHandler.ts [hunk 2]
```diff
@@ -8,15 +8,20 @@ class DiscordMessageLinkHandler extends EventHandler {
...
 
 	async handle(message: Message): Promise<void> {
-		const messagePreviewService = MessagePreviewService.getInstance();
 		const messageRegex = /https:\/\/(ptb\.)?discord(app)?\.com\/channels\//gm;
 
-		if (message.content.startsWith("!")) return;
-
 		if (message.content.match(messageRegex)) {
 			const linkIndex = message.content.search(messageRegex);
+			if (linkIndex == -1) return;
```
Comment (Jason2605) [inline src/event/handlers/DiscordMessageLinkHandler.ts]: This is the change i was suggesting, there's no need for `.match` as `.search` returns -1 if there was no match.

```suggestion
		const linkIndex = message.content.search(messageRegex);
		
		if (linkIndex !== -1) {
```

**Review by LamboCreeper — APPROVED** [review]

**Review by Jason2605 — APPROVED** [review]
